[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.3",
    "numpy>=2.4.6",
    "onnxruntime>=1.26.0",
    "pillow>=12.2.0",
    "python-multipart>=0.0.30",
    "rfdetr[plus]>=1.7.1",
    "sqlmodel>=0.0.38",
    "torch>=2.12.0",
    "uvicorn[standard]>=0.48.0",
    "websockets>=16.0",
]
